export const homeComingInvitees = [
  "sasiya",
  "madda",
  "dilini",
  "batta",
  "oshan",
  "amila-and-nipuni",
  "ruveesha-and-hasinthaka",
  "prabodhi-and-asanka",
  "hashan",
  "pathuma",
  "raviya",
  "dombe",
  "vihanga",
  "dula",
  "isuru-malli",
  "madusha-malli",
  "hasindu-malli",
] as const;
